// const VALID_LOGIN = 'VALID_LOGIN';
// const INVALID_PASSWORD = 'INVALID_PASSWORD';
// const USER_NOT_FOUND = 'USER_NOT_FOUND';

// // module.exports = { VALID_LOGIN, INVALID_PASSWORD, USER_NOT_FOUND };
// module.exports = VALID_LOGIN;
